services:
  - type: web
    name: currency-report-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: GEMINI_API_KEY
        sync: false  # You'll set this manually in Render dashboard